apiVersion: v1
kind: Service
metadata:
  name: app
spec:
  type: {{ .Values.app.service.type }}
  ports:
  - port: {{ .Values.app.service.port }}
    targetPort: {{ .Values.app.service.port }}
    nodePort: {{ .Values.app.service.nodePort }}
  selector:
    app: my-app
